import logging
import os
import requests
from datetime import datetime

logger = logging.getLogger("JiraService")

class JiraService:
    def __init__(self):
        # In production, these would come from environment variables
        self.api_token = os.getenv("JIRA_API_TOKEN")
        self.site_url = os.getenv("JIRA_SITE_URL", "indmoney.atlassian.net")
        self.user_email = os.getenv("JIRA_USER_EMAIL", "chsk.nitw@gmail.com")
        self.base_url = f"https://{self.site_url}/rest/api/3"
        self.is_mock = self.api_token is None or self.api_token == ""

    def create_ticket(self, review_data):
        """
        Creates a Jira ticket for the given review data.
        Returns the Jira Key (e.g., PROD-101) or a Mock Key if in dev mode.
        """
        try:
            summary = f"VOC Alert [{review_data['platform'].upper()}]: {review_data['user_name']}"
            description = (
                f"*Rating:* {review_data['rating']} stars\n"
                f"*Feedback:* {review_data['review_text']}\n\n"
                f"--- \n"
                f"Generated by INDMoney Pulse on {datetime.now().strftime('%Y-%m-%d %H:%M')}"
            )

            if self.is_mock:
                mock_id = f"JIRA-{datetime.now().strftime('%S%f')[:4]}"
                logger.info(f"MOCK JIRA: Created ticket {mock_id} for review")
                return f"[SIMULATED] {mock_id}"

            # Production API Call
            project_key = os.getenv("JIRA_PROJECT_KEY", "PROD")
            
            payload = {
                "fields": {
                    "project": {"key": project_key},
                    "summary": summary,
                    "description": {
                        "type": "doc",
                        "version": 1,
                        "content": [
                            {
                                "type": "paragraph",
                                "content": [{"type": "text", "text": description}]
                            }
                        ]
                    },
                    "issuetype": {"name": "Task"}
                }
            }
            
            response = requests.post(
                f"{self.base_url}/issue", 
                json=payload, 
                auth=(self.user_email, self.api_token),
                timeout=10
            )
            
            if response.status_code == 201:
                key = response.json().get('key')
                logger.info(f"LIVE JIRA: Created ticket {key}")
                return key
            else:
                logger.error(f"Jira API Error ({response.status_code}): {response.text}")
                return f"ERR-{response.status_code}"

        except Exception as e:
            logger.error(f"Failed to create Jira ticket: {e}")
            return None
