import { NextResponse } from 'next/server';

export async function POST(request, { params }) {
  const { id } = params;
  try {
    const body = await request.json();
    const pmName = body.assigned_to;
    const reviewData = body.review_data || {};
    
    // Check if Jira credentials are provided in Vercel Environment Variables
    const apiToken = process.env.JIRA_API_TOKEN;
    const siteUrl = process.env.JIRA_SITE_URL || 'indmoney.atlassian.net';
    const userEmail = process.env.JIRA_USER_EMAIL || 'chsk.nitw@gmail.com';
    const projectKey = process.env.JIRA_PROJECT_KEY || 'PROD';
    
    if (apiToken && apiToken !== "mock_token_here") {
       // --- LIVE JIRA INTEGRATION ---
       const authHeader = `Basic ${Buffer.from(`${userEmail}:${apiToken}`).toString('base64')}`;
       
       const summary = `VOC Alert [${reviewData.platform?.toUpperCase() || 'APP'}]: ${reviewData.user_name || 'User'} assigned to ${pmName}`;
       const description = `*Rating:* ${reviewData.rating || 0} stars\n*Feedback:* ${reviewData.review_text || 'No text provided'}\n\n*Assigned Owner:* ${pmName}\n\n--- \nGenerated by INDMoney Pulse Dashboard.`;
       
       const jiraPayload = {
           fields: {
               project: { key: projectKey },
               summary: summary,
               description: {
                   type: "doc",
                   version: 1,
                   content: [
                       {
                           type: "paragraph",
                           content: [{ type: "text", text: description }]
                       }
                   ]
               },
               issuetype: { name: "Task" }
           }
       };

       const response = await fetch(`https://${siteUrl}/rest/api/3/issue`, {
           method: 'POST',
           headers: {
               'Authorization': authHeader,
               'Accept': 'application/json',
               'Content-Type': 'application/json'
           },
           body: JSON.stringify(jiraPayload)
       });

       if (response.ok) {
           const data = await response.json();
           return NextResponse.json({ success: true, jira_id: data.key, assigned_to: pmName });
       } else {
           const errorText = await response.text();
           console.error("Jira API Error:", errorText);
           return NextResponse.json({ success: false, error: "Jira API Error", details: errorText }, { status: response.status });
       }
    }
    
    // --- ERROR: Missing Credentials ---
    return NextResponse.json({ 
      success: false, 
      error: "Missing Jira Credentials", 
      details: "Please add JIRA_API_TOKEN to Vercel Environment Variables." 
    }, { status: 400 });
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
